pub struct Logging {
    pub ledger_logging_value: bool,
    pub ledger_duplicate_logging_value: bool,
    pub ledger_rollback_logging_value: bool,
    pub vote_logging_value: bool,
    pub rep_crawler_logging_value: bool,
    pub election_fork_tally_logging_value: bool,
    pub election_expiration_tally_logging_value: bool,
    pub network_logging_value: bool,
    pub network_timeout_logging_value: bool,
    pub network_message_logging_value: bool,
    pub network_publish_logging_value: bool,
    pub network_packet_logging_value: bool,
    pub network_keepalive_logging_value: bool,
    pub network_node_id_handshake_logging_value: bool,
    pub network_telemetry_logging_value: bool,
    pub network_rejected_logging_value: bool,
    pub node_lifetime_tracing_value: bool,
    pub insufficient_work_logging_value: bool,
    pub log_ipc_value: bool,
    pub bulk_pull_logging_value: bool,
    pub work_generation_time_value: bool,
    pub upnp_details_logging_value: bool,
    pub timing_logging_value: bool,
    pub active_update_value: bool,
    pub log_to_cerr_value: bool,
    pub flush: bool,
    pub max_size: usize,
    pub rotation_size: usize,
    pub stable_log_filename: bool,
    pub min_time_between_log_output_ms: i64,
    pub single_line_record_value: bool,
}

impl Logging {
    pub fn new() -> Self {
        Self {
            ledger_logging_value: false,
            ledger_duplicate_logging_value: false,
            ledger_rollback_logging_value: false,
            vote_logging_value: false,
            rep_crawler_logging_value: false,
            election_fork_tally_logging_value: false,
            election_expiration_tally_logging_value: false,
            network_logging_value: true,
            network_timeout_logging_value: false,
            network_message_logging_value: false,
            network_publish_logging_value: false,
            network_packet_logging_value: false,
            network_keepalive_logging_value: false,
            network_node_id_handshake_logging_value: false,
            network_telemetry_logging_value: false,
            network_rejected_logging_value: false,
            node_lifetime_tracing_value: false,
            insufficient_work_logging_value: true,
            log_ipc_value: true,
            bulk_pull_logging_value: false,
            work_generation_time_value: true,
            upnp_details_logging_value: false,
            timing_logging_value: false,
            active_update_value: false,
            log_to_cerr_value: false,
            flush: true,
            max_size: 128 * 1024 * 1024,
            rotation_size: 4 * 1024 * 1024,
            stable_log_filename: false,
            min_time_between_log_output_ms: 5,
            single_line_record_value: false,
        }
    }
}
