FROM alpine:3.22 AS builder

ARG COMPILER=gcc
ARG NANO_NETWORK=live

COPY ./scripts/ci/prepare/linux /tmp/prepare
RUN sh /tmp/prepare/prepare-alpine.sh

COPY ./ /tmp/src
WORKDIR /tmp/src

ARG BUILD_TYPE=RelWithDebInfo
ARG NANO_TEST=OFF
ARG NANO_TRACING=OFF
ARG COVERAGE=OFF
ARG CMAKE_SANITIZER=""
ARG CI_TAG=DEV_BUILD
ARG CI_VERSION_PRE_RELEASE=OFF
ARG SANITIZER

RUN /root/.cargo/bin/rustup target add x86_64-unknown-linux-musl

ENV PATH="/root/.cargo/bin:${PATH}"
RUN cd main && cargo build --release --target x86_64-unknown-linux-musl \
    && strip /tmp/src/target/x86_64-unknown-linux-musl/release/rsnano_node

RUN echo ${NANO_NETWORK} >/etc/nano-network

FROM alpine:3.22

RUN addgroup -g 1000 rsban && \
    adduser -u 1000 -G rsban -s /bin/sh -D rsban

COPY --from=builder /tmp/src/target/x86_64-unknown-linux-musl/release/rsnano_node /usr/bin/rsnano_node
COPY --from=builder /etc/nano-network /etc/nano-network
COPY scripts/docker/node/config /usr/share/nano/config
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

WORKDIR /root
USER root

ENV PATH="${PATH}:/usr/bin"
ENTRYPOINT ["/usr/bin/rsnano_node"]
CMD ["node", "run"]

ARG REPOSITORY=banano/rsban
LABEL org.opencontainers.image.source="https://github.com/$REPOSITORY"
