@startuml "Split crates"

[core]
[ledger]
[store_lmdb]
[messages]
[network]
[daemon]
[node]
[main]
[rpc_messages]
[rpc_server]
[rpc_client]
[websocket_messages]
[websocket_server]

folder "nullables"{
[fs]
[clock]
[random]
[tcp]
[lmdb]
[http_client]
[output_tracker]
}

[main] --> [daemon]
[daemon] --> [node]
[daemon] --> [rpc_server]
[rpc_server] --> [node]
[rpc_server] --> [rpc_messages]
[rpc_client] --> [rpc_messages]
[rpc_messages] --> [core]
[node] --> [ledger]
[node] --> [messages]
[node] --> [network]
[node] --> [websocket_server]
[websocket_server] --> [websocket_messages]
[websocket_messages] --> [core]
[messages] --> [core]
[network] --> [core]
[ledger] --> [store_lmdb]
[store_lmdb] --> [core]
[core] --> "nullables"

@enduml
