@startuml "Confirmation Height"
class UnboundedMode {
    process(block, callbacks)
}

class BoundedMode{
    process(block, callbacks)
}

class AutomaticMode{
    process(block, callbacks)
}

class ConfirmationHeightProcessor{
    add(block)
    run(mode)
}
class Ledger

package "Logic"{
    enum ConfirmationHeightMode{
        Autmatic
        Unbounded
        Bounded
    }

    class WriteDetails
    class WriteDetailsQueue

    class SingleAccountCementer
    class MultiAccountCementer
    class BatchWriteSizeManager {
        current()
    }
}

package "Values"{
    struct UpdateConfirmationHeight{
        account
        new_cemented_frontier
        new_height
        num_blocks_cemented
    }
}


UnboundedMode --> Ledger
UnboundedMode --> BatchWriteSizeManager

BoundedMode --> Ledger
BoundedMode --> WriteDetailsQueue
BoundedMode --> MultiAccountCementer
BoundedMode --> BatchWriteSizeManager

MultiAccountCementer --> SingleAccountCementer
MultiAccountCementer --> BatchWriteSizeManager
MultiAccountCementer --> WriteDetailsQueue

SingleAccountCementer --> UpdateConfirmationHeight
SingleAccountCementer --> WriteDetails

WriteDetailsQueue --> WriteDetails

AutomaticMode --> ConfirmationHeightMode
AutomaticMode --> BoundedMode
AutomaticMode --> UnboundedMode
AutomaticMode --> Ledger
AutomaticMode --> BatchWriteSizeManager

ConfirmationHeightProcessor --> AutomaticMode

@enduml