@startuml "Split crates"

[nullables]
[core]
[ledger]
[messages]
[node]
[main]
[ffi]

folder "nullables"{
[output_tracker]
[nullable_fs]
[nullable_tcp]
}

[main] --> [node]
[node] --> [core]
[node] --> [ledger]
[node] --> [messages]
[node] --> "nullables"
[ledger] --> "nullables"
[ffi] --> [ledger]
[ffi] --> [node]

@enduml