@startuml "Split crates"

[core]
[ledger]
[store_lmdb]
[messages]
[network]
[node]
[main]
[ffi]
[C++ node]
[rpc_messages]
[rpc_server]
[rpc_client]

folder "nullables"{
[fs]
[clock]
[random]
[tcp]
[lmdb]
[http_client]
[output_tracker]
}

[C++ node] --> [ffi]
[main] --> [node]
[main] --> [rpc_server]
[rpc_server] --> [node]
[rpc_server] --> [rpc_messages]
[rpc_client] --> [rpc_messages]
[rpc_messages] --> [core]
[node] --> [ledger]
[node] --> [messages]
[node] --> [network]
[messages] --> [core]
[network] --> [core]
[ledger] --> [store_lmdb]
[store_lmdb] --> [core]
[ffi] --> [node]
[core] --> "nullables"

@enduml