@startuml "Split crates"

[rsnano_core]
[rsnano_store_traits]
[rsnano_ledger]
[rsnano_application]
[rsnano_node]
[rsnano_ffi]

database "LMDB"{
    [rsnano_store_lmdb]
}

database "In Memory"{
    [rsnano_store_mem]
}

[rsnano_store_traits] --> [rsnano_core]
[rsnano_ledger] --> [rsnano_store_traits]
[rsnano_store_lmdb] --> [rsnano_store_traits]
[rsnano_store_mem] --> [rsnano_store_traits]
[rsnano_application] --> [rsnano_ledger]
[rsnano_node] --> [rsnano_store_lmdb]
[rsnano_node] --> [rsnano_store_mem]
[rsnano_node] --> [rsnano_application]
[rsnano_ffi] --> [rsnano_node]

@enduml