@startuml "Port Blockprocessor"
class block_processor #PaleGoldenRod
class active_transactions
class election
class confirmation_solicitor
class election_status #PaleGreen
class online_reps #PaleGreen
class ledger #PaleGreen
class vote_generator
class vote_broadcaster
class vote_processor
class vote_spacing #PaleGreen
class wallets #PaleGreen
class local_vote_history #PaleGreen
class inactive_vote_cache #PaleGoldenRod
class signature_checker #PaleGreen

interface message_visitor

package "Networking"{
class network
class rep_crawler
}

package "Channels"{
class peer_exclusion #PaleGreen
class tcp_message_manager #PaleGreen
class channel_tcp_wrapper #PaleGreen
class channel_tcp #PaleGreen
class outbound_bandwidth_limiter #PaleGreen
class syn_cookies #PaleGreen
class tcp_server #PaleGreen
class tcp_channels
class tcp_server_factory
class network_filter #PaleGreen
}

package "Bootstrapping"{
    class bulk_pull_server
    class bulk_pull_account_server
    class frontier_req_server
    class bulk_push_server
    class bootstrap_message_visitor
    class request_response_visitor_factory
}

active_transactions --> election
confirmation_solicitor --> network

election --> active_transactions
election --> election_status
election --> online_reps
election --> ledger
election --> block_processor
election --> vote_generator
election --> network
election --> local_vote_history
election --> inactive_vote_cache
election ..> confirmation_solicitor

vote_generator --> vote_broadcaster
vote_broadcaster --> vote_processor
vote_generator --> vote_spacing
vote_generator --> ledger
vote_generator --> wallets

vote_processor --> signature_checker
vote_processor --> active_transactions
vote_processor --> online_reps
vote_processor --> rep_crawler 
vote_processor --> ledger

rep_crawler --> tcp_channels
rep_crawler --> online_reps
rep_crawler --> ledger
rep_crawler --> active_transactions
rep_crawler --> vote_processor

network --> network_filter
network --> tcp_channels
network --> rep_crawler
network --> syn_cookies

tcp_channels --> tcp_server_factory
tcp_channels --> outbound_bandwidth_limiter
tcp_channels --> syn_cookies
tcp_channels --> tcp_message_manager
tcp_channels --> channel_tcp_wrapper
tcp_channels --> peer_exclusion

tcp_server_factory --> tcp_server
tcp_server --> syn_cookies
tcp_server --> network_filter

channel_tcp_wrapper --> channel_tcp
channel_tcp --> tcp_server

bulk_pull_server --> tcp_server
bulk_pull_account_server --> tcp_server

bootstrap_message_visitor ..|> message_visitor
bootstrap_message_visitor --> bulk_pull_account_server
bootstrap_message_visitor --> bulk_pull_server
bootstrap_message_visitor --> frontier_req_server
bootstrap_message_visitor --> bulk_push_server

request_response_visitor_factory --> bootstrap_message_visitor

@enduml