ARG ENV_REPOSITORY=simpago/rsnano-env
FROM ${ENV_REPOSITORY}:base

RUN apt-get update -qq && apt-get install -yqq \
..

ARG REPOSITORY=simpago/rsnano-node
LABEL org.opencontainers.image.source https://github.com/$REPOSITORY
