FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && apt-get install -yqq \
build-essential \
g++ \
wget \
python3 \
zlib1g-dev \
curl \
git \
cmake \
pkg-config

RUN apt-get update -qq && apt-get install -yqq \
qtbase5-dev \
qtchooser \
qt5-qmake \
qtbase5-dev-tools \
valgrind \
xorg xvfb xauth xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y \
    && git clone https://github.com/AndrewGaspar/corrosion.git \
    && cmake -Scorrosion -Bbuild -DCMAKE_BUILD_TYPE=Release \
    && cmake --build build --config Release \
    && cmake --install build --config Release 

ARG REPOSITORY=simpago/rsnano-node
LABEL org.opencontainers.image.source https://github.com/$REPOSITORY
