name: Publish Docker image
on:
  push:
    branches: ['test2']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  rsban_node:
    runs-on: ubuntu-latest:22.04
    steps:
       - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
       - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
       - name: Cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
            
       - name: Build and push
        run: |
             docker build . --tag ghcr.io/notcutecatatall/rsban_nodeo:latest
             docker run ghcr.io/notcutecatatall/rsban_node:latest
             docker push ghcr.io/notcutecatatall/rsban_node:latest
